Fixed ModuleExprScore Error with single modules
When there's only 1 module mod_scores becomes an array instead of data.frame and causes:
Error: <simpleError in `colnames<-`(`*tmp*`, value = mods): attempt to set 'colnames' on an object with less than two dimensions> during colnames
Added code so that if mod_scores is not data.frame change it to data.frame